# Generated by Django 3.1.4 on 2021-01-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0002_area_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='close_time',
            field=models.CharField(max_length=30),
        ),
    ]
