# Generated by Django 3.1.4 on 2021-01-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0003_auto_20210104_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualanimal',
            name='animal_id',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='IndividualAnimal',
        ),
    ]
