# Generated by Django 3.1.4 on 2021-01-08 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scientific_id', models.CharField(max_length=30)),
                ('animal_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('conservation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('H_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=30)),
                ('continent', models.CharField(max_length=30)),
                ('terrian', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('zoo_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('number_of_visitors', models.IntegerField()),
                ('number_of_sites', models.IntegerField()),
                ('number_of_categories', models.IntegerField()),
                ('avg_temp', models.FloatField()),
                ('ticket_price', models.IntegerField()),
                ('rain_per_year', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zookeeper',
            fields=[
                ('keeper_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('join_time', models.IntegerField()),
                ('department', models.CharField(max_length=30)),
                ('birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('year_in', models.IntegerField()),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=30)),
                ('nearby', models.CharField(max_length=30)),
                ('theme', models.CharField(max_length=30)),
                ('close_time', models.CharField(max_length=30)),
                ('distance', models.FloatField()),
                ('zoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.zoo')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.area'),
        ),
        migrations.AddField(
            model_name='animal',
            name='h_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.habitat'),
        ),
    ]
