# Generated by Django 3.1.4 on 2020-12-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('scientific_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('animal_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_id', models.CharField(max_length=30)),
                ('weather', models.CharField(max_length=30)),
                ('continent', models.CharField(max_length=30)),
                ('terrian', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('zoo_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('atrribute', models.CharField(max_length=30)),
                ('number_of_visits', models.IntegerField()),
                ('number_of_sites', models.IntegerField()),
                ('number_of_categories', models.IntegerField()),
                ('avg_temp', models.FloatField()),
                ('ticket_price', models.IntegerField()),
                ('rain_per_year', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zookeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeper_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('department', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('supervisor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAnimal',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('year_in', models.IntegerField()),
                ('Animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=30)),
                ('nearby', models.CharField(max_length=30)),
                ('theme', models.CharField(max_length=30)),
                ('close_time', models.TimeField()),
                ('zoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.zoo')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.area'),
        ),
        migrations.AddField(
            model_name='animal',
            name='h_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.habitat'),
        ),
    ]
