# Generated by Django 3.1.4 on 2021-01-08 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30)),
                ('temperature_low', models.FloatField()),
                ('temperature_high', models.FloatField()),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.animal')),
                ('keeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.zookeeper')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.area')),
                ('zoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.zoo')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('relation', models.CharField(max_length=30)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.animal')),
            ],
        ),
    ]
