# Generated by Django 3.1.4 on 2021-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualanimal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualanimal',
            name='idividual_id',
            field=models.CharField(max_length=30),
        ),
    ]
