# Generated by Django 3.1.4 on 2020-12-09 04:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('zoo_info', '0002_auto_20201207_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal_id',
            new_name='animal_name',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='scientific_name',
            new_name='scientific_id',
        ),
        migrations.RenameField(
            model_name='individualanimal',
            old_name='Animal_id',
            new_name='animal_id',
        ),
        migrations.RenameField(
            model_name='individualanimal',
            old_name='name',
            new_name='idividual_id',
        ),
        migrations.RemoveField(
            model_name='zoo',
            name='atrribute',
        ),
    ]
