# Generated by Django 3.1.4 on 2021-01-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0002_dependent_facility_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zookeeper',
            name='department',
        ),
        migrations.AddField(
            model_name='zookeeper',
            name='area_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='zoo_info.area'),
            preserve_default=False,
        ),
    ]
