# Generated by Django 3.1.4 on 2021-01-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0002_auto_20210106_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualanimal',
            old_name='idividual_id',
            new_name='name',
        ),
    ]
