# Generated by Django 3.1.4 on 2020-12-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0003_auto_20201209_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoo',
            old_name='number_of_visits',
            new_name='number_of_visitors',
        ),
    ]
