# Generated by Django 3.1.4 on 2021-01-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0003_auto_20210117_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
