# Generated by Django 3.1.4 on 2021-01-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0004_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
