# Generated by Django 3.1.4 on 2021-01-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0004_auto_20210106_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scientific_id', models.CharField(max_length=30)),
                ('animal_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('conservation', models.CharField(max_length=30)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.area')),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.habitat')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('year_in', models.IntegerField()),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_info.animal')),
            ],
        ),
    ]
