# Generated by Django 3.1.4 on 2021-01-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0004_auto_20201209_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zookeeper',
            old_name='age',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='zookeeper',
            old_name='experience',
            new_name='join_time',
        ),
        migrations.RemoveField(
            model_name='zookeeper',
            name='supervisor',
        ),
    ]
