# Generated by Django 3.1.4 on 2021-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0005_remove_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/zoo_info'),
        ),
    ]
