# Generated by Django 3.1.4 on 2021-01-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0005_auto_20210103_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zookeeper',
            name='id',
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='keeper_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
