# Generated by Django 3.1.4 on 2021-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_info', '0006_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualanimal',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/zoo_info'),
        ),
    ]
